# Site
title: keynary
subtitle: ''
description: 'stay hungry, stay foolish'
keywords:
author: keynary
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://stoic-yang.github.io/
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directories
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# Code blocks
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true

# Markdown
marked:
  gfm: true
  breaks: true
  dompurify: false
  prependRoot: true
  postAsset: true
  lazyload: true

# Lists
index_generator:
  path: ''
  per_page: 10
  order_by: -date
default_category: uncategorized
per_page: 10
pagination_dir: page

# Dates
date_format: YYYY-MM-DD
time_format: HH:mm
updated_option: date

# Theme
theme: ink

# Feed
feed:
  limit: 20
  order_by: -date
  tag_dir: false
  category_dir: false
  rss:
    enable: false
  atom:
    enable: true
    output: atom.xml
  jsonFeed:
    enable: false
archive_generator:
  per_page: 0
  yearly: true
  monthly: true
